language: scala
sudo: false
jdk: oraclejdk8
scala: 2.12.4
services:
- docker
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
addons:
  sonarcloud:
    organization: tourlive
    token:
      secure: EcZjbUvI7Udjz+5S89EmAo/gd12iIl36Aes4Bjp5rfdYu8SzJVVkJMS7E1TxDKv3HYWxP/iY0zscOHLQUur5CbfkLTpS6yZMoBm9NTIhU7RHddMctf0nxnJwcLNZ7s27ZxG4IZXUbI4ieM59WRcME1EFoc3bvYw/m7CISedSMjjNPnxLAc4kQ0Zw/YyPoGtep58DMsGpip+1ABI0D65ffyaJkis0xIF01lOZvyHATkBszOcWSXgMHaoOxtERJ7J5dgeYJmHhOmBuHxcIkgnPH7HurmtESXmkHxN9ZKFNOpmiC4WUPZypOpJA9tpkF2jv2ziHQpRzfHi6yPmTP9F5AJlHVkNRwgIMTSr4SNIvFalaPOdVMF7r/GFk95qQc2rvjwEhdJjDFsB9ZnKUoJRJLS90u6K0VXS04YjE8YLVZ2Kf9qL/5yJLQAj4URZfbqJbHkc4qmwW1I7pA2lkfnUGx45YRMkItgNvlNJCZbZfT9PWgLl/q0QBshrNU/+BbTGeCZFHyXsOJSypXpqVFAUfnBtBSSZnT7Cf1qIYN9Qul07d1dwPJEseYZVZL77aVGU/Co+oS1GMoMyLO2KYFB02sV6jKztFk/LLSa4+cvt88FkKP5nWJAkHrkKEyi2fPoojPCUViaHKVHjQvwJqKpVO4vWC6KSRYJQbEi3+P1OBgRE=
    github_token:
      secure: mNICF14xnS2R+rEf+TTHbHQfhl7riaC0XVb++uLmi21q0+SuWNjWrz2ECQXmYIUm7lTuJtNQ0M0z5XyVxboK2twDPeMLtZ2dFEovKY1M4NGUI7sUmmY+8EDC+N/nPRIMG1GV3D34i9wsTXZmROyuLEwcx63jhF/cTah3cXhQu+/Vlw/6jYo5N3QalTNx82/T/ze7cCs+NCD9a4T34zjC+yqUxStOOgCAzFDHJQEzxyMPdRdDWgPLn5M43hCEWq5Xr7IoC4tgVQOffB1T+9GVIe6/sMSnbXP7s01PiAPveXWwhnWfig7fXtTcBk93T4h12rsgJCw+clGZUESiRI7ziZtxELo3JOMMhicBTUXpQlfNr7wYqFCf4xkhwKjE7eZCb0XS1UOqEJ1EWqIuSSlgtcHh3Woz06TNXHPdk7IJc/E61DwDiskglWlyWXTTcWhBX2OAZ/kVPhZLJRJmht8NDPOR8LoT8A036v6Mmw8GA47P6rcEwC4cUYfDsE8uo+BWIjFRSVWlf/C0bfld6bvJX/yBNAC4Re/QUpo1GQje6haM9AchrtVyENJrCLn5PqA1ISNPN7qiif6tnVSZhLVmlZhg8m+EwF7MbdTojQHeVcxZr7rhscOSNmknh9fT5HV8LXnXiULr5AJYTl0kj/l6BPDQYZxZBoAbuR4ISvIK6zw=
script:
- sbt test
- sonar-scanner
- find $HOME/.sbt -name "*.lock" | xargs rm
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_8bd8278227a2_key -iv $encrypted_8bd8278227a2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
